### ISSUE TITLE
Any item dupe with Actually Additions

### ISSUE THREAD

**Issue by Sonic2423** [thiakil/Applied-Energistics-2#65] opened 2017-09-03 21:49 UTC
Put a storage bus with higher priority than everything else on a crate and set to desired block. Now get an export bus with 4 acceleration cards and export the desired item to the same crate. now place a stack of the desired item in the crate and a single one next to it. now the crate fills up with the item.

video:
https://youtu.be/5prAYjeh7_w

running:
ActuallyAdditions-1.12.1-r119.jar
applied-llamagistics-1.12-rv5-beta-7.jar
forge 1.12.1-14.22.0.2467

Works in singleplayer and multiplayer. only works with storage crates. normal chests and strongboxes from TE arent affected.

originally found on my server with forge 2444, AA-r119 and applied-llamagistics-1.12-rv5-beta-7 with various other mods.

Also opened an issue at AAs side but it seems like it is similar to an issue RefinedStorage also had:
https://github.com/Ellpeck/ActuallyAdditions/issues/915
https://github.com/raoulvdberge/refinedstorage/issues/1407#issuecomment-321193102

**Comment by thiakil** [comment] 2017-09-04 02:45
The issue seems to be incompatible (opposite) assumptions where the docs are unclear. Will look into it.

**Comment by andr9528** [comment] 2017-09-15 14:45
Had this happen with nothing pulling it out automatically and the crates being the lowest priority (0) and the only storage other than my 2 storage drawer walls. items being in crates also seems to simply duplicate, with nothing as much as moving them an inch. Went from having 1 medium storage crate 10 min ago to having 2 now.

**Comment by thiakil** [comment] 2017-09-15 14:51
Yup, their item handler is bad

**Comment by Ozzymud** [comment] 2017-09-17 04:38
Don't be so quick, I set up the same system in ATM3 but tried various other inventories. I was able to get the same result using a skystone chest as well as a rustic barrel.

**Comment by thiakil** [comment] 2017-09-17 05:42
So show me the skystone chest setup. If you can produce it with that it's not the same as OP, because it uses the Forge wrapper which doesn't expose its internal ItemStack

**Comment by Ozzymud** [comment] 2017-09-17 10:44
It was identical to the video posted by the OP, the only item altered was the crate, replaced with a chest and then a wood barrel. I wanted to see the bug for myself so I copied his design block for block originally. Only when it worked did I remove the AA crate and replace it with a skystone chest, it continued to dupe items when a stack+1 was put in the chest with the export and storage bus set to that item with 4 acceleration cards in the export bus.

**Comment by Ozzymud** [comment] 2017-09-21 06:56
![image1](https://user-images.githubusercontent.com/6426344/30681794-deb516d6-9e5b-11e7-883c-f97750cb86cc.png)

The image above shows the minimum needed to replicate. This was done in the latest FTB Unstable for 1.12.1 using only AE2 items (see hotbar of screenshot). No priorities were even set (only needed if using other storage).  

Items used:
Creative Energy Cell (also works in SSP/SMP with normal power options)
3 cables (any type works)
1 export bus with 4 acceleration cards set to export the item to be duped
1 storage bus set to store the item to be duped
1 skystone chest with an initial inventory of 64+1 item (any item that stacks to 64)  

Inventories that **did not work** in FTB Unstable:
Wooden Storage Crate - Immersive Engineering
Chest - Vanilla
Hopper - Vanilla
Blaze Hopper - Natura
Framed Chest - Bibliocraft
Draconium Chest - Draconic Evolution
Iron Chest (any chest/shulker) - Iron Chest
Ender-Link Chest - Multi-Storage

Inventories that **did work** in FTB Unstable:
Skystone Chest - Applied Energistics 2
Slightly-Larger Chest - Extra Utilities 2
Iron/Gold/Diamond Reinforeced Chest - QuantumStorage
(any) Storage Crate - Actually Additions


That's all that I could think of to test. The setup in the image posted works(to an end user) the same as the OP's setup. The setup in the image uses only items from AE2. I'm not a coder so know nothing about Forge wrappers or the internal ItemStack. What I do know is that I can easily replicate the dupe using the method provided by the OP. Holler if you need any more of the grunt work done :)

**Comment by thiakil** [comment] 2017-09-21 06:58
Thanks!

**Comment by thiakil** [comment] 2017-09-21 12:55
Cannot reproduce at all with a sky stone chest.

**Comment by Ozzymud** [comment] 2017-09-21 17:08
I don't know what to say, tested on 2 packs now in 1.12.x, works on both All The Mods 3 and FTB Unstable.

Minecraft Version: 1.12.1
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_111, Oracle Corporation
MinecraftForge v14.22.1.2485
appliedenergistics2-rv5-alpha-4 - same as ATM3 and FTB Unstable although the log shows an updated version - [AE2 VersionChecker/INFO] [AE2:C]: Newer version is available: rv4-stable-1 (found) > rv5-alpha-4 (current) but this is what twitch offered.  

Was able to re-create with JUST ae2 installed to a fresh profile in the twitch launcher. Will try to get the rv4-stable-1 from twitch and try with it.

Edit: Oh my, I feel stupid now... this is the Applied Llamagistics page... I just went and got the newest version of it and re-tested, the skystone chest didn't work in the test pack. I also re-tested with all the other inventories, no worries there and the crate from AA seems to be fixed in ActuallyAdditions-1.12.1-r120.

**Comment by Ozzymud** [comment] 2017-09-21 17:10
![image1](https://user-images.githubusercontent.com/6426344/30708825-febc5c6a-9eb4-11e7-9e48-4d71db6243b0.png)

rv4-stable-1 not found in the twitch launcher... will manually download and report back

**Comment by thiakil** [comment] 2017-09-22 00:41
Heh that's ok. It's weird though that the Skystone Chest one doesn't happen in AL - I'm fairly certain I don't do the extra copy that Yueh added to his (because the default forge impl *does* do it, unlike his commit message implies)

Gonna close this for now. If it can be reproduced with a Vanilla chest and/or a Sky Stone chest, we can revisit. Otherwise it is a problem in the other mods' item handler.

**Closed as completed by thiakil** 2017-09-22 00:41 UTC
Labels: external interaction
