### ISSUE TITLE
Autocrafting causes some sort of disconnect/hangs AE

### ISSUE THREAD

**Issue by DoomSquirter** [thiakil/Applied-Energistics-2#23] opened 2017-07-15 19:29 UTC
Queueing anything to autocraft on SMP causes the ae system to look functional, but is missing all the items in any terminal.  It does this simultaneously to everyone on the server as well.

#### Description
entire storage is on storage busses, no disk drives.  
created 8 interfaces, 32 molecular assemblers, one 64k crafting storage.  
made a pattern for a pattern and put in interface, queued some patterns and clicked next and it just never returns from there.  
go back to ae terminals and I have zero items shown in any terminal.  simultaneously all users on at the time had their ae's become inaccessible as well.
I restarted server a couple times testing this and no logs are generated.  typed something before I did what I did and after and nothing in logs in between.
tried to autocraft just one to be sure it wasn't stuck on calculating something and it did the same, waited 10 minutes and it never came back.

#### Environment
SMP
running farscapes 1.1.0-r3 on official server

- Minecraft Version: 
1.11
- AE2 Version: 
applied-llamagistics-rv5-alpha-2
- Forge Version: 
forge-1.11.2-13.20.1.2393-universal.jar

**Comment by thiakil** [comment] 2017-07-16 03:04
Update to the newest llamagistics version, enable crafting logging in the configuration and post your full server log. 

Also try with just llamagistics loaded. If you cannot reproduce with just AL, you'll need to find the minimum combination that does cause the issue.

**Comment by DoomSquirter** [comment] 2017-07-16 11:24
we have an update planned, will test the updated version + crafting logging enabled and see what happens.  Just letting you know.

didn't say this in main issue, but it bears saying.  Thank you so much for forking this.  I'm so damn happy to have AE2 back.  SOOO happy :)

**Comment by DoomSquirter** [comment] 2017-07-16 22:05
applied-llamagistics-1.11.2-rv5-alpha-5 was updated on server.
Applicable section for misc:
    misc {
        B:Achievements=true
        B:CraftingLog=true
        B:Creative=true
        B:DebugLogging=false
        B:GrinderLogging=false
        B:IntegrationLogging=false
        B:LightDetector=true
        B:LogSecurityAudits=false
        B:Logging=true
        B:PacketLogging=false
        B:UnsupportedDeveloperTools=false
        B:UpdateLogging=false
        B:WebsiteRecipes=false
    }
does any of the other logging like debug logging need to be enabled to see the crafting log?  
I saw nothing in logs whatsoever for ae and problem definately persisted.

**Comment by DoomSquirter** [comment] 2017-07-16 22:07
one other point.  another person stated that the items are 'accessible', they just don't show up in terminal.  So, for instance, if you pasted a recipe in from jei, you can still retrieve outputted item.  you just don't see anything in the terminal itself.

**Comment by thiakil** [comment] 2017-07-17 00:39
`B:CraftingLog=true` I believe that's the one. Any crafting jobs should generate logs with that.

I have not had any issue with crafting jobs in my testing.

**Comment by DoomSquirter** [comment] 2017-07-18 23:17
well, when the problem happens, with the config set like above, nothing shows up in the logs ever.  so we don't need debug logging on in addition tho?

obviously it's a conflict of some kind then.  I will try in ssp and see if I can replicate issue then if I can, try to identify what mod is doing it but it will more than likely take some time to do that.
edit since github was acting wierd.

**Comment by thiakil** [comment] 2017-07-19 01:33
On closer inspection it looks like it might only log on completion, and any other useful info is only on debug level (which forge by default won't output).

Could you enable that `DebugLogging` option, [save this xml file](https://gist.github.com/thiakil/cf4bb204d31987290339cf5812c98c74) somewhere, and run the server with `-Dlog4j.configurationFile=file://<path-to-xml>` (in case of windows you'll need to use forward slashes instead of backslashes)

This will send all AL debug messages to both the server console and the log file (and as a bonus things will be in colour)

**Comment by DoomSquirter** [comment] 2017-07-19 09:28
so one thing I noticed just now, if I hit next twice, about 2-5 seconds in between, I get the actual craft window and it shows the pattern and the items it says are missing, but actually are in the system.

Also I realize now that I can reset the AE w/o actually restarting server by yanking one controller that's connected to power, wait a few seconds and replace it.

and weird enough, if I do this a couple times, the bug stops happening, tho the crafting doesn't actually start and it is erroneously stating the components aren't in the system, they most definately are.

I'll post logs soon.  waiting on confirmation from admin.

**Comment by leagris** [comment] 2017-07-19 10:59
[fml-server-3.log](https://gist.githubusercontent.com/leagris/77c32db6e2519d9edf10ca10e5f837fe/raw/671effe58bb04a0e9f6e9aa5471cde0205c1a354/fml-server-3.log)

Near line 28584
```
[06:35:00] [Server thread/DEBUG] [AE2:S/]: Exception: 
java.lang.RuntimeException: Slot 1136 not in valid range - [0,9)
	at net.minecraftforge.items.ItemStackHandler.validateSlotIndex(ItemStackHandler.java:209) ~[ItemStackHandler.class:?]
	at net.minecraftforge.items.ItemStackHandler.extractItem(ItemStackHandler.java:127) ~[ItemStackHandler.class:?]
	at com.buuz135.industrial.tile.misc.BlackHoleControllerTile$BlackHoleControllerHandler.extractItem(BlackHoleControllerTile.java:249) ~[BlackHoleControllerTile$BlackHoleControllerHandler.class:?]
	at appeng.parts.misc.ItemHandlerAdapter.extractItems(ItemHandlerAdapter.java:141) ~[ItemHandlerAdapter.class:?]
	at appeng.parts.misc.ItemHandlerAdapter.extractItems(ItemHandlerAdapter.java:56) ~[ItemHandlerAdapter.class:?]
	at appeng.me.storage.MEPassThrough.extractItems(MEPassThrough.java:63) ~[MEPassThrough.class:?]
	at appeng.me.storage.MEInventoryHandler.extractItems(MEInventoryHandler.java:117) ~[MEInventoryHandler.class:?]
	at appeng.me.storage.NetworkInventoryHandler.extractItems(NetworkInventoryHandler.java:229) ~[NetworkInventoryHandler.class:?]
	at appeng.me.cache.NetworkMonitor.extractItems(NetworkMonitor.java:93) ~[NetworkMonitor.class:?]
	at appeng.crafting.MECraftingInventory.<init>(MECraftingInventory.java:139) ~[MECraftingInventory.class:?]
	at appeng.crafting.CraftingJob.<init>(CraftingJob.java:90) ~[CraftingJob.class:?]
	at appeng.me.cache.CraftingGridCache.beginCraftingJob(CraftingGridCache.java:505) ~[CraftingGridCache.class:?]
	at appeng.core.sync.packets.PacketCraftRequest.serverPacketData(PacketCraftRequest.java:101) [PacketCraftRequest.class:?]
	at appeng.core.sync.network.AppEngServerPacketHandler$1.call(AppEngServerPacketHandler.java:56) [AppEngServerPacketHandler$1.class:?]
	at appeng.core.sync.AppEngPacket.func_148833_a(AppEngPacket.java:104) [AppEngPacket.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[06:35:00] [Server thread/DEBUG] [AE2:S/]: Exception: 

```

**Comment by thiakil** [comment] 2017-07-19 12:21
That's a bug in whatever mod provides `BlackHoleControllerTile` - AL's item handler adaptor just iterates through 0 to slots-reported-by-IItemHandler... It's also kind bad manners for it to let an exception propagate when it seems like it could be validating the slot before sending it to the Forge class

Just had a look, and yep, their `getSlots()` method is not returning what it is supposed to be at all! I've reported it to them [here](https://github.com/Buuz135/Industrial-Foregoing/issues/17). For now please don't use that block with a Storage Bus

As for why the error is stopping others from accessing the system I am not quite sure yet, there's possibly a path that's not getting caught. I'll add some extra stupid-proofing beyond that so your craft can continue too.

Bonus info: both the Terminal GUI and the graft confirm GUI (the one where it says whether or not you have the items) both use the same packet to update the counts. So if something fails and Forge/MC stops processing that packet type that would be why everything stops working...

Thanks for your help tracking this down!

**Comment by thiakil** [comment] 2017-07-19 13:23
new version released which should fix this (pending on curse at time of writing, available on GH if you don't need curse)

**Closed as completed by thiakil** 2017-07-19 13:23 UTC
Labels: external interaction

**Comment by leagris** [comment] 2017-07-19 13:28
:bowing_woman: Thank you very much dude !

**Comment by DoomSquirter** [comment] 2017-07-20 10:17
Thanks very much for all of this.  :)
just fyi, that update fixed the issue, even with the black hole unit hooked up to storage bus.  worked like a charm.
